apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cosy-backend
spec:
  destination:
    namespace: cosy
    server: https://kubernetes.default.svc
  source:
    path: backend
    repoURL: https://github.com/Magenta-Mause/cosy-deployment
    targetRevision: HEAD
  sources: []
  project: cosy
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      enabled: true

