apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cosy-infrastructure
spec:
  destination:
    namespace: cosy
    server: https://kubernetes.default.svc
  source:
    path: infrastructure
    repoURL: https://github.com/Magenta-Mause/cosy-deployment
    targetRevision: HEAD
  project: cosy
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      enabled: true

