services:
  backend:
    image: ghcr.io/magenta-mause/cosy-backend:sha-b174093
    ports:
      - "127.0.0.1:8080:8080"
    environment:
      - SPRING_DATASOURCE_USERNAME=${POSTGRES_USER}
      - SPRING_DATASOURCE_PASSWORD=${POSTGRES_PASSWORD}
      - SPRING_DATASOURCE_URL=jdbc:postgresql://database:5432/cosydb
    depends_on:
      - database
    networks:
      - cosy-network

  frontend:
    image: ghcr.io/magenta-mause/cosy-frontend:387669dad567df6fd00d8575f7f3073e6ef55f36
    ports:
      - "127.0.0.1:3000:80"
    depends_on:
      - backend
    networks:
      - cosy-network

  database:
    image: postgres:16
    environment:
      - POSTGRES_DB=cosydb
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - cosy-network

volumes:
  postgres-data:

networks:
  cosy-network:

