apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: cosy-backend
  namespace: cosy
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
spec:
  rules:
    - host: cosy.jannekeipert.de
      http:
        paths:
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: cosy-backend
                port:
                  number: 80
  tls:
    - hosts:
        - cosy.jannekeipert.de
      secretName: multi-domain-cert   

