apiVersion: v1
kind: Service
metadata:
  name: cosy-frontend
  namespace: cosy
spec:
  selector:
    app: cosy-frontend
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
  type: ClusterIP

