all:
  hosts:
    vps:
      ansible_host: 80.158.76.109
      ansible_user: deploy
      ansible_ssh_private_key_file: ~/.ssh/github_deploy
      ansible_python_interpreter: /usr/bin/python3
      
      # Deployment configuration
      deployment_path: /opt/cosy
      docker_compose_path: /opt/cosy/docker

